# Generated by Django 4.2 on 2023-04-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='Variation',
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
    ]
