# Generated by Django 4.2 on 2023-04-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_productvariation_variation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
