# Generated by Django 4.2 on 2023-05-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
