# Generated by Django 4.2 on 2023-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_chasis_number_product_engine_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_registration_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
