# Generated by Django 4.2 on 2023-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_first_registration_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
